# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pijp-dti.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 666)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 8, 8, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 8, 2, 1, 1)
        self.image_frame = QtWidgets.QVBoxLayout()
        self.image_frame.setObjectName("image_frame")
        self.gridLayout.addLayout(self.image_frame, 8, 9, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 8, 10, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_code = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_code.sizePolicy().hasHeightForWidth())
        self.label_code.setSizePolicy(sizePolicy)
        self.label_code.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_code.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_code.setAlignment(QtCore.Qt.AlignCenter)
        self.label_code.setObjectName("label_code")
        self.verticalLayout_3.addWidget(self.label_code)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.button_open = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_open.sizePolicy().hasHeightForWidth())
        self.button_open.setSizePolicy(sizePolicy)
        self.button_open.setAutoRepeat(False)
        self.button_open.setFlat(False)
        self.button_open.setObjectName("button_open")
        self.verticalLayout_3.addWidget(self.button_open)
        self.button_skip = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_skip.sizePolicy().hasHeightForWidth())
        self.button_skip.setSizePolicy(sizePolicy)
        self.button_skip.setStyleSheet("")
        self.button_skip.setObjectName("button_skip")
        self.verticalLayout_3.addWidget(self.button_skip)
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_clear.sizePolicy().hasHeightForWidth())
        self.button_clear.setSizePolicy(sizePolicy)
        self.button_clear.setStyleSheet("")
        self.button_clear.setObjectName("button_clear")
        self.verticalLayout_3.addWidget(self.button_clear)
        self.button_hide = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_hide.sizePolicy().hasHeightForWidth())
        self.button_hide.setSizePolicy(sizePolicy)
        self.button_hide.setObjectName("button_hide")
        self.verticalLayout_3.addWidget(self.button_hide)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_opacity = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_opacity.sizePolicy().hasHeightForWidth())
        self.label_opacity.setSizePolicy(sizePolicy)
        self.label_opacity.setAlignment(QtCore.Qt.AlignCenter)
        self.label_opacity.setObjectName("label_opacity")
        self.verticalLayout_2.addWidget(self.label_opacity)
        self.slider_opacity = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_opacity.sizePolicy().hasHeightForWidth())
        self.slider_opacity.setSizePolicy(sizePolicy)
        self.slider_opacity.setMaximum(100)
        self.slider_opacity.setSingleStep(10)
        self.slider_opacity.setProperty("value", 50)
        self.slider_opacity.setOrientation(QtCore.Qt.Horizontal)
        self.slider_opacity.setObjectName("slider_opacity")
        self.verticalLayout_2.addWidget(self.slider_opacity)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result.sizePolicy().hasHeightForWidth())
        self.label_result.setSizePolicy(sizePolicy)
        self.label_result.setObjectName("label_result")
        self.verticalLayout_4.addWidget(self.label_result)
        self.button_pass = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_pass.sizePolicy().hasHeightForWidth())
        self.button_pass.setSizePolicy(sizePolicy)
        self.button_pass.setObjectName("button_pass")
        self.verticalLayout_4.addWidget(self.button_pass)
        self.button_edit = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_edit.sizePolicy().hasHeightForWidth())
        self.button_edit.setSizePolicy(sizePolicy)
        self.button_edit.setObjectName("button_edit")
        self.verticalLayout_4.addWidget(self.button_edit)
        self.button_fail = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_fail.sizePolicy().hasHeightForWidth())
        self.button_fail.setSizePolicy(sizePolicy)
        self.button_fail.setObjectName("button_fail")
        self.verticalLayout_4.addWidget(self.button_fail)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_comment = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_comment.sizePolicy().hasHeightForWidth())
        self.label_comment.setSizePolicy(sizePolicy)
        self.label_comment.setObjectName("label_comment")
        self.verticalLayout_7.addWidget(self.label_comment)
        self.line_comment = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_comment.sizePolicy().hasHeightForWidth())
        self.line_comment.setSizePolicy(sizePolicy)
        self.line_comment.setObjectName("line_comment")
        self.verticalLayout_7.addWidget(self.line_comment)
        self.verticalLayout.addLayout(self.verticalLayout_7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem7)
        self.button_submit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_submit.sizePolicy().hasHeightForWidth())
        self.button_submit.setSizePolicy(sizePolicy)
        self.button_submit.setStyleSheet("")
        self.button_submit.setObjectName("button_submit")
        self.verticalLayout.addWidget(self.button_submit)
        self.gridLayout.addLayout(self.verticalLayout, 8, 7, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QC Tool"))
        self.label_code.setText(_translate("MainWindow", "ScanCode"))
        self.button_open.setText(_translate("MainWindow", "Open Editor"))
        self.button_skip.setText(_translate("MainWindow", "Skip"))
        self.button_clear.setText(_translate("MainWindow", "Clear Edits"))
        self.button_hide.setText(_translate("MainWindow", "Hide"))
        self.label_opacity.setText(_translate("MainWindow", "Opacity:"))
        self.label_result.setText(_translate("MainWindow", "Result:"))
        self.button_pass.setText(_translate("MainWindow", "Pass"))
        self.button_edit.setText(_translate("MainWindow", "Edit"))
        self.button_fail.setText(_translate("MainWindow", "Fail"))
        self.label_comment.setText(_translate("MainWindow", "Comments:"))
        self.button_submit.setText(_translate("MainWindow", "Submit"))

